export enum OpenfortOAuthProvider {
    ACCELBYTE = "accelbyte",
    FIREBASE = "firebase",
    LOOTLOCKER = "lootlocker",
    SUPABASE = "supabase",
    PLAYFAB = "playfab",
    CUSTOM = "custom",
    OIDC = "oidc",
    GOOGLE = "google",
    TWITTER = "twitter",
    FACEBOOK = "facebook",
    DISCORD = "discord",
    EPIC_GAMES = "epic_games",
    TELEGRAM = "telegram",
    TELEGRAM_MINI_APP = "telegramMiniApp",
}
